name: CodeCov

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cd:
    name: CodeCov
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Test
        run: |
          CVPKG=$(go list ./... | grep -v mocks | tr '\n' ',')
          go test -coverpkg=${CVPKG} -coverprofile=coverage.out -covermode=count  ./...
